// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderServiceOrder struct {
	OrderID    string
	CustomerID pgtype.UUID
	Workflow   string
	Status     string
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
}

type OrderServiceOrderItem struct {
	OrderItemID string
	OrderID     string
	Name        string
	CreatedAt   pgtype.Timestamptz
	ModifiedAt  pgtype.Timestamptz
}
