version: '3.8'
services:
  database-postgres:
    image: postgres:15.4-alpine3.18
    container_name: database-postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", $DB_NAME, "-U", $DB_USER ]
      interval: 5s
    networks:
      - lambda-network
    ports:
      - '5432:5432'

  aws-localstack:
    image: localstack/localstack:3.0.0
    container_name: aws-localstack
    volumes:
      - ./localstack:/etc/localstack/init:ro
    networks:
      - lambda-network
    ports:
      - '4566:4566'

networks:
  lambda-network:
    name: lambda-network
    driver: bridge
