version: 0.2


phases:
  install:
    commands:
      - yum install -y bind-utils
  build:
    commands:
      - echo "Running tests"
      - nslookup 13ike9sgy0.execute-api.eu-central-1.amazonaws.com
      # disable iam auth in api gateway for testing
      - curl https://13ike9sgy0.execute-api.eu-central-1.amazonaws.com/test/v1/orders