name: Build, test and deploy

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  GO_VERSION: 1.21.4
  NODE_VERSION: 20.10.0
  CDK_VERSION: 2.113.0

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            files:
              - '.github/workflows/**'
              - 'go.mod'
              - 'go.sum'
              - 'libraries/**'
              - '${{ inputs.project-path }}/**'

  changes-gate:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.files-changed == 'true' }}

  test:
    runs-on: ubuntu-latest
    needs:
      - changes-gate
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: install dependencies
        run: mage dep:install

      - name: generate dependencies
        run: mage dep:generate

      - name: start test dependencies
        run: mage docker:up

      - name: run integration tests
        run: mage test:integration

      - name: output test dependencies logs
        if: failure()
        run: mage docker:logs

      - name: stop test dependencies
        if: always()
        run: mage docker:down

  deploy:
    runs-on: ubuntu-latest
    needs:
      - changes-gate
    if: ${{ needs.changes.outputs.files-changed == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    environment: ${{ inputs.region }}-${{ inputs.environment }}
    env:
      REGION: ${{ inputs.region }}
      ENVIRONMENT: ${{ inputs.environment }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install aws-cdk
        run: npm install -g aws-cdk@${{ env.CDK_VERSION }}

      - name: install dependencies
        run: mage dep:install

      - name: generate dependencies
        run: mage dep:generate

      - name: build lambdas
        run: mage lambda:build

      - name: show cdk synth
        run: mage cdk:synth

      - name: show cdk diff
        run: mage cdk:diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: deploy cdk stack
        run: mage cdk:deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}