on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            files:
              - '.github/workflows/**'
              - 'go.mod'
              - 'go.sum'
              - 'libraries/**'
              - '${{ inputs.project-path }}/**'

  test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.files-changed == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
          cache: true
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: start test dependencies
        run: mage docker:up

      - name: run integration tests
        run: mage test:integration

      - name: output test dependencies logs
        if: failure()
        run: mage docker:logs

      - name: stop test dependencies
        if: always()
        run: mage docker:down

  deploy:
    runs-on: ubuntu-latest
    needs:
      - changes
      - test
    if: ${{ needs.changes.outputs.files-changed == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    environment: ${{ inputs.region }}-${{ inputs.environment }}
    env:
      REGION: ${{ inputs.region }}
      ENVIRONMENT: ${{ inputs.environment }}
      VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
          cache: true
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: install aws-cdk
        run: npm install -g aws-cdk@2.110.0

      - name: show cdk diff
        run: mage cdk:diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: deploy cdk stack
        run: mage cdk:deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}