on:
  workflow_call:
    inputs:
      component-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changed
        with:
          list-files: json
          filters: |
            files:
              - '.github/workflows/build.yaml'
              - '.github/workflows/lint.yaml'
              - '.github/workflows/test.yaml'
              - '.github/workflows/deploy.yaml'
              - 'go.mod'
              - 'go.sum'
              - 'libraries/**'
              - '${{ inputs.component-path }}/**'

  changes-gate:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.files-changed == 'true' }}
    steps:
      - name: Changes detected
        run: echo "File changes detected"

  lint:
    uses: ./.github/workflows/lint.yaml
    needs:
      - changes-gate
    secrets: inherit
    with:
      component-path: ${{ inputs.component-path }}

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - changes-gate
    secrets: inherit
    with:
      component-path: ${{ inputs.component-path }}

#  deploy:
#    uses: ./.github/workflows/deploy.yaml
#    needs:
#      - changes-gate
#      - lint
#      - test
#    secrets: inherit
#    with:
#      node-version: ${{ inputs.node-version }}
#      cdk-version: ${{ inputs.cdk-version }}
#      project-path: ${{ inputs.project-path }}
#      region: ${{ inputs.region }}
#      environment: ${{ inputs.environment }}