name: Build, test and deploy service

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      cdk-version:
        required: true
        type: string

      project-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      files-changed: ${{ steps.changed.outputs.files }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          list-files: json
          filters: |
            files:
              - '.github/workflows/**'
              - 'go.mod'
              - 'go.sum'
              - 'libraries/**'
              - '${{ inputs.project-path }}/**'

  changes-gate:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.files-changed == 'true' }}
    steps:
      - name: changes detected
        run: echo "File changes detected"

  lint:
    uses: ./.github/workflows/lint.yaml
    needs:
      - changes-gate
    secrets: inherit
    with:
      go-version: ${{ inputs.go-version }}
      project-path: ${{ inputs.project-path }}

  test:
    uses: ./.github/workflows/test.yaml
    needs:
      - changes-gate
    secrets: inherit
    with:
      go-version: ${{ inputs.go-version }}
      project-path: ${{ inputs.project-path }}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs:
      - changes-gate
      - lint
      - test
    secrets: inherit
    with:
      go-version: ${{ inputs.go-version }}
      node-version: ${{ inputs.node-version }}
      cdk-version: ${{ inputs.cdk-version }}
      project-path: ${{ inputs.project-path }}
      region: ${{ inputs.region }}
      environment: ${{ inputs.environment }}