on:
  workflow_call:
    inputs:
      src:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ inputs.src }}