on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    environment: ${{ inputs.region }}-${{ inputs.environment }}
    env:
      REGION: ${{ inputs.region }}
      ENVIRONMENT: ${{ inputs.environment }}
      VERSION: ${{ inputs.version }}
    steps:
      - if: steps.changes.outputs.src == 'true'
        name: cdk diff
        run: mage cdk:diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - if: steps.changes.outputs.src == 'true'
        name: cdk deploy
        run: mage cdk:deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}