name: Deploy service

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      cdk-version:
        required: true
        type: string

      project-path:
        required: true
        type: string
      region:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.region }}-${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    env:
      REGION: ${{ inputs.region }}
      ENVIRONMENT: ${{ inputs.environment }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install aws-cdk
        run: npm install -g aws-cdk@${{ inputs.cdk-version }}

      - name: Build lambdas
        run: mage lambda:build

      - name: Run cdk synth
        run: mage cdk:synth

      - name: Show cdk diff
        run: mage cdk:diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy cdk stack
        run: mage cdk:deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}