name: Lint component

on:
  workflow_call:
    inputs:
      component-path:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
          working-directory: ${{ inputs.component-path }}