name: Lint component

on:
  workflow_call:
    inputs:
      component-path:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.component-path }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2