// Package incoming provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package incoming

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Sigv4Scopes = "sigv4.Scopes"
)

// Defines values for OrderStatus.
const (
	OrderCanceled   OrderStatus = "order_canceled"
	OrderCompleted  OrderStatus = "order_completed"
	OrderInProgress OrderStatus = "order_in_progress"
	OrderPlaced     OrderStatus = "order_placed"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          int       `json:"code"`
	CorrelationId string    `json:"correlation_id"`
	Message       *string   `json:"message,omitempty"`
	Method        string    `json:"method"`
	Path          string    `json:"path"`
	Timestamp     time.Time `json:"timestamp"`
}

// OrderItemRequest defines model for OrderItemRequest.
type OrderItemRequest struct {
	Name string `json:"name"`
}

// OrderItemResponse defines model for OrderItemResponse.
type OrderItemResponse struct {
	Name string `json:"name"`
}

// OrderRequest defines model for OrderRequest.
type OrderRequest struct {
	CustomerId openapi_types.UUID `json:"customer_id"`
	Items      []OrderItemRequest `json:"items"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	CreatedAt  time.Time           `json:"created_at"`
	CustomerId openapi_types.UUID  `json:"customer_id"`
	Items      []OrderItemResponse `json:"items"`
	OrderId    string              `json:"order_id"`
	Status     OrderStatus         `json:"status"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse = []OrderResponse

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = ErrorResponse

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	// CustomerId The customer id determines the customer of orders returned
	CustomerId *openapi_types.UUID `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// Limit The limit determines the number of orders returned
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The offset determines the skipped orders
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = OrderRequest
